apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-cost-exporter
  labels:
    app.kubernetes.io/name: aws-cost-exporter
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-cost-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aws-cost-exporter
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: aws-cost-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "python", "main.py", "-c", "/exporter_config.yaml" ]
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: metrics
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          volumeMounts:
          - name: config-volume
            mountPath: /exporter_config.yaml
            subPath: exporter_config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: aws-cost-exporter-config
