apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.awsCredentialsSecret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.awsCredentialsSecret.accessKeyIdKey }}: {{ .Values.awsAccessKeyId | b64enc }}
  {{ .Values.awsCredentialsSecret.secretAccessKeyKey }}: {{ .Values.awsSecretAccessKey | b64enc }}
