{
 "title": "00_Kubernetes_Application_Logs",
 "description": "Logs collected from Kubernetes, stored in Loki",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" },
   { "name": "container", "query": "label_values(container)" }
  ]
 },
 "panels": [
  {
   "title": "Logs Count",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\", container =~\"$container\"} [$__interval]))",
     "legendFormat": "Log count"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", container =~\"$container\"}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", container =~\"$container\"} !~ \"WARN\" |= \"ERROR\" |= \"error\" !~ \"INFO\" !~ \"info\" !~ \"warn\" !~ \"DEBUG\" !~ \"debug\""
    }
   ]
  },
  {
   "title": "Logs - WARN",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", container =~\"$container\"} !~ \"ERROR\" |= \"WARN\" |= \"warn\" !~ \"INFO\" !~ \"info\" !~ \"error\" !~ \"DEBUG\" !~ \"debug\""
    }
   ]
  }
 ]
}