{
 "title": "00_Node_Info",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Node Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Nodes",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(up{job=~\"kubernetes-nodes\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Node_Capacity_Types",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 18, "x": 6, "y": 1 },
     "targets": [
      {
       "expr": "sum(up{job=~\"kubernetes-nodes\"}) by (node,eks_amazonaws_com_capacityType,kubernetes_io_hostname)",
       "legendFormat": "{{kubernetes_io_hostname}} AND {{eks_amazonaws_com_capacityType}}"
      }
     ]
    },
    {
     "title": "Node_Capacity_Types",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(up{job=~\"kubernetes-nodes\"}) by (node,eks_amazonaws_com_capacityType)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Node Status",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (node) (kube_node_status_condition{condition=\"Ready\", status=\"true\"}) == 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Node Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_time_seconds - node_boot_time_seconds",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Disk Pressure",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "kube_node_status_condition{condition=\"DiskPressure\", status=\"true\"}\r\n",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Node Pod Capacity",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "kube_node_status_capacity{resource=\"pods\"}\r\n",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Node Load Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "process" } },
     "targets": [
      { "expr": "node_load1", "legendFormat": "{{node}}" }
     ]
    }
   ]
  },
  {
   "title": "Node Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by(instance,node) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))*100)",
       "legendFormat": "{{node}} AND {{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100)",
       "legendFormat": "{{node}} AND {{instance}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_free_bytes{mountpoint=\"/\"}) / node_filesystem_size_bytes{mountpoint=\"/\"} * 100",
       "legendFormat": "{{node}} AND {{instance}}"
      }
     ]
    },
    {
     "title": "Disk I/O Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total[5m])\r\n",
       "legendFormat": "{{node}} AND {{instance}}"
      }
     ]
    },
    {
     "title": "Node Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_network_receive_bytes_total[5m]))\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Node Outbound Traffic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_network_transmit_bytes_total[5m]))\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Node Network Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "Error/sec" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_network_receive_errs_total[5m]))\r\n",
       "legendFormat": "{{instance}} Receive Errors"
      },
      {
       "expr": "sum by (instance) (rate(node_network_transmit_errs_total[5m]))\r\n",
       "legendFormat": "{{instance}} Transmit Errors"
      }
     ]
    }
   ]
  }
 ]
}