{
 "title": "00_Pods_Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=~\"Active\"},namespace)"
    }
   },
   {
    "name": "pod_name",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod_name\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{pod!=\"\", pod=~\"$pod_name\", namespace=~\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "(sum (container_memory_working_set_bytes{pod!=\"\", pod=~\"$pod_name\", namespace=~\"$namespace\"}) by (pod))/(1024*1024*1024)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "pod metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Limit Vs Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(sum (kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod_name\",resource=~\"cpu\"}) by (pod))",
     "legendFormat": "Limit {{pod}}"
    },
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{pod!=\"\", pod=~\"$pod_name\", namespace=~\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "Usage {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Limit Vs Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "(sum (kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod_name\",resource=~\"memory\"}) by (pod))/(1024*1024*1024)",
     "legendFormat": "Limit {{pod}}"
    },
    {
     "expr": "(sum (container_memory_working_set_bytes{pod!=\"\", pod=~\"$pod_name\", namespace=~\"$namespace\"}) by (pod))/(1024*1024*1024)",
     "legendFormat": "Usage {{pod}}"
    }
   ]
  },
  {
   "title": "Container Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (container,pod) (container_threads{namespace=~\"$namespace\",container=~\"$container\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "current container info",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\",pod!~\"\"}) by (pod,container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=~\"$namespace\",pod!~\"\"}) by (pod,image_spec)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (container,pod,instance) (container_threads{namespace=~\"$namespace\",container=~\"$container\",pod!~\"\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum (container_memory_working_set_bytes{pod!~\"\", pod=~\"$pod_name\", namespace=~\"$namespace\",container!~\"\"}) by (container,pod)) / (1024*1024*1024)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{pod!~\"\", pod=~\"$pod_name\", namespace=~\"$namespace\",container!~\"\"}[5m]) * 100) by (container,pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}