{
 "title": "00_Service Monitoring",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "target",
    "query": {
     "query": "label_values(probe_success,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=~\".*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Global Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=~\"$target\"}",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "$target status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "target",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_success{job=~\"$target\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "HTTP Duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "probe_http_duration_seconds{job=~\"$target\"}",
       "legendFormat": "{{ phase }}"
      }
     ]
    },
    {
     "title": "Probe Duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "probe_duration_seconds{job=~\"$target\"}",
       "legendFormat": "seconds"
      }
     ]
    },
    {
     "title": "HTTP Status Code",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_http_status_code{job=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Version",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_http_version{job=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_http_ssl{job=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL Expiry",
     "type": "stat",
     "gridPos": { "h": 2, "w": 10, "x": 4, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_ssl_earliest_cert_expiry{job=~\"$target\"} - time()"
      }
     ]
    },
    {
     "title": "Average Probe Duration",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 14, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(probe_duration_seconds{job=~\"$target\"})"
      }
     ]
    },
    {
     "title": "Average DNS Lookup",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(probe_dns_lookup_time_seconds{job=~\"$target\"})"
      }
     ]
    }
   ]
  }
 ]
}